cf:
  token: "apiToken"
  zone: "zoneID"
api:
  # "ipip.net", "gh.ink" or customize API
  # "ipip.net" only supports IPv4
  # Only support Raw API that responds to a single IP address
  # Like response 200 "1.1.1.1"
  # Customize API address should be with protocol
  # Leave option blank to disable it
  v4: "ipip.net"
  v6: "https://example.com"
record:
  name: "test.example.com"
  # In second
  period: 60
log:
  file: "logs/app.log"
  maxSize: 100
  maxBackups: 10
  maxAge: 30
  compress: true