cf:
  token: "apiToken"
  zone: "zoneID"
api:
  # "ipip.net", "gh.ink" or customise API
  # Only support Raw API that responds to a single IP address
  # Like response 200 "1.1.1.1"
  # Customise API address should be with protocol
  # Leave option blank to disable it
  v4: "ipip.net"
  v6: "https://example.com"
record:
  name: "test.example.com"
  # In second
  period: 60
log:
  file:
    all: "logs/app.log"
    err: "logs/err.log"
  max_size: 5
  max_backups: 100
  max_age: 30
  compress: true